print('CADASTRO')
nome_ = input('Nome: ')
email_ = input('Email: ')
senha_ = input('Senha: ')
print('')
print('Cadastrado')
print('Nome:', nome_)
print('Email:', email_)
print('Senha:', senha_)